title: Piranha305 GameDev
description: > # this means to ignore newlines until "baseurl:"
    Hey, I am a professional software developer / tester, 
    I love to do game development in my free time.
    My favorite game engine is Construct 3.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Armndo Alonso # add your name
author-img: icon_128x128.png # add your photo
about-author: I am a professional software developer / tester, I love to do game development in my free time. # add description
social-twitter: piranha_305 # add your Twitter handle
social-youtube: https://www.youtube.com/channel/UCxYVUzTKpE8Y1vZMyvV6Xdg #add youtube url
social-itch: https://piranha305.itch.io/ # add your Facebook handle
social-github: armandoalonso # add your Github handle
social-linkedin: armandoalonso # add your Linkedin handle
social-email: armandoalonso1@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
